interface DeliverFixEnv {}

interface DeliverFixBody {
  owner?: unknown;
  repo?: unknown;
  baseBranch?: unknown;
  filePath?: unknown;
  fixedCode?: unknown;
  title?: unknown;
  body?: unknown;
  token?: unknown;
}

function text(value: unknown, max: number) {
  return typeof value === 'string' ? value.trim().slice(0, max) : '';
}

function privateJson(data: unknown, init: ResponseInit = {}) {
  const headers = new Headers(init.headers);
  headers.set('Cache-Control', 'no-store');
  headers.set('Vary', 'Cookie');
  return Response.json(data, { ...init, headers });
}

function validSegment(value: string) {
  return /^[A-Za-z0-9_.-]+$/.test(value);
}

function validPath(value: string) {
  return value.length > 0 && value.length <= 500 && !value.startsWith('/') && !value.includes('..');
}

function githubHeaders(token: string) {
  return {
    Accept: 'application/vnd.github+json',
    Authorization: `Bearer ${token}`,
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'D-Bugger-Real-Fix-Delivery',
    'Content-Type': 'application/json',
  };
}

async function githubRequest(url: string, token: string, init?: RequestInit) {
  const response = await fetch(url, { ...init, headers: { ...githubHeaders(token), ...(init?.headers || {}) } });
  const data = await response.json().catch(() => ({})) as any;
  if (!response.ok) throw new Error(data.message || `GitHub request failed (${response.status})`);
  return data;
}

function base64Utf8(value: string) {
  return btoa(Array.from(new TextEncoder().encode(value), (byte) => String.fromCharCode(byte)).join(''));
}

export const onRequestPost: PagesFunction<DeliverFixEnv> = async ({ request }) => {
  try {
    const body = await request.json() as DeliverFixBody;
    const owner = text(body.owner, 100);
    const repo = text(body.repo, 100);
    const baseBranch = text(body.baseBranch, 200) || 'main';
    const filePath = text(body.filePath, 500);
    const fixedCode = text(body.fixedCode, 300000);
    const title = text(body.title, 240) || 'fix(auto): verified D-Bugger repair';
    const prBody = text(body.body, 10000) || 'Automated repair generated and reviewed by D-Bugger.';
    const token = text(body.token, 300);
    if (!token) return privateJson({ error: 'A GitHub token is required for real branch and pull-request delivery.' }, { status: 401 });
    if (!validSegment(owner) || !validSegment(repo) || !validPath(filePath) || !fixedCode) return privateJson({ error: 'Valid owner, repository, file path, and corrected code are required.' }, { status: 400 });

    const baseRef = await githubRequest(`https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(baseBranch)}`, token);
    const baseSha = baseRef.object?.sha;
    if (typeof baseSha !== 'string') throw new Error('GitHub did not return the base branch commit.');
    const branch = `dbugger/fix-${Date.now().toString(36)}`;
    await githubRequest(`https://api.github.com/repos/${owner}/${repo}/git/refs`, token, { method: 'POST', body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }) });

    const existing = await githubRequest(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}?ref=${encodeURIComponent(baseBranch)}`, token);
    const commit = await githubRequest(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`, token, {
      method: 'PUT',
      body: JSON.stringify({ message: title, content: base64Utf8(fixedCode), branch, sha: existing.sha, committer: { name: 'D-Bugger', email: 'agent@d-bugger.dev' }, author: { name: 'D-Bugger', email: 'agent@d-bugger.dev' } }),
    });
    const pullRequest = await githubRequest(`https://api.github.com/repos/${owner}/${repo}/pulls`, token, {
      method: 'POST',
      body: JSON.stringify({ title, head: branch, base: baseBranch, body: `${prBody}\n\n---\nGenerated by D-Bugger after repository-grounded analysis and validation.`, maintainer_can_modify: false }),
    });
    return privateJson({ delivered: true, branch, commitSha: commit.commit?.sha, pullRequestNumber: pullRequest.number, pullRequestUrl: pullRequest.html_url });
  } catch (error: any) {
    console.error('Real GitHub fix delivery failed:', error);
    return privateJson({ delivered: false, error: error?.message || 'GitHub delivery failed.' }, { status: 502 });
  }
};
