create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.monitored_repos (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  repo_name text not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.check_runs (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  repo_name text not null,
  commit_sha text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.research_notes (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.working_style_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.user_preferences enable row level security;
alter table public.monitored_repos enable row level security;
alter table public.check_runs enable row level security;
alter table public.research_notes enable row level security;
alter table public.working_style_events enable row level security;

drop policy if exists user_preferences_owner on public.user_preferences;
create policy user_preferences_owner on public.user_preferences for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists monitored_repos_owner on public.monitored_repos;
create policy monitored_repos_owner on public.monitored_repos for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists check_runs_owner on public.check_runs;
create policy check_runs_owner on public.check_runs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists research_notes_owner on public.research_notes;
create policy research_notes_owner on public.research_notes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists working_style_events_owner on public.working_style_events;
create policy working_style_events_owner on public.working_style_events for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
